[general]
import = ["~/tokyonight/extras/alacritty/tokyonight_night.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1.1"

[font]
size = 16
normal = { family = "monospace", style = "Regular" }
bold = { family = "monospace", style = "Bold" }
italic = { family = "monospace", style = "Italic" }
bold_italic = { family = "monospace", style = "Bold Italic" }

[scrolling]
history = 32768

[cursor]
style = { shape = "Beam", blinking = "Never" }

[window]
blur = true
decorations = "Full"
dimensions = { columns = 160, lines = 36 }
dynamic_padding = true
opacity = 0.92
padding = { x = 4, y = 4 }
startup_mode = "Windowed"
